### PR TITLE
added smart india hackthon to our Router project

### PR DESCRIPTION
**Pull request by chethancm2001**
merge

### CODE REVIEW

**Comment by zrqx** [comment]
The file `q` has commit details. Do we need to incude it as is ? or Should we just highlight the Contributors names in README itself ?

**Comment by chethancm2001** [comment]
sorry i mistakely added this i will remove and i will make new PR

**Comment by chethancm2001** [comment]
closing this PR !!

**Comment by zrqx** [comment]
Good work by the way.

**Pull request closed without merging**
